### ISSUE TITLE
Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by mhurwicz** [evanlucas/learnyoumongo#21]
I had some problems on install:
https://github.com/evanlucas/learnyoumongo/issues/20

But it seemed that mongo was available:

```
mhurwicz:~/workspace $ mongod --version
db version v2.6.11
2015-11-05T19:20:17.076+0000 git version: d00c1735675c457f75a12d530bee85421f0c5548
```

But now trying to execute this code:

```
  var mongo = require('mongodb').MongoClient
    mongo.connect('mongodb://localhost:27017/learnyoumongo', function(err, db) {
      // db gives access to the database
    })
```

I get the following:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/find.js:1:78)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by evanlucas** [comment]
You'll need to `npm install mongodb`

**Comment by mhurwicz** [comment]
Evan - Thanks for the reply. That seems to have worked.  For others who may run across this, on Cloud 9 I also got things working by editing package.JSON to add mongodb as a dependency:  

```
  "dependencies": {
    "async": "~0.2.8",
    "express": "~3.2.4",
    "socket.io": "~0.9.14",
    "mongodb":"~2.6.11"
  }
```

and then using `npm link mongodb`

I based this solution  on this:
http://stackoverflow.com/questions/14226410/node-js-cannot-find-module-mongodb

**Comment by Buildit978** [comment]
Thank You
