### ISSUE TITLE
Blinking menu

### ISSUE THREAD

**Issue by ddzieduch** [evanlucas/learnyoumongo#22]
After run learnyoumongo i see blinking menu.
When close (CTRL + C) i get error:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write after end
>     at writeAfterEnd (/usr/local/lib/node_modules/learnyoumongo/node_modules/readable-stream/lib/_stream_writable.js:144:12)
>     at DuplexWrapper.Writable.write (/usr/local/lib/node_modules/learnyoumongo/node_modules/readable-stream/lib/_stream_writable.js:192:5)
>     at ReadStream.passDataToMenu (/usr/local/lib/node_modules/learnyoumongo/node_modules/workshopper/menu.js:69:16)
>     at emitOne (events.js:77:13)
>     at ReadStream.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at ReadStream.Readable.push (_stream_readable.js:110:10)
>     at TTY.onread (net.js:523:20)

OS X 10.6.8
npm 3.3.9
node 4.2.1
learnyoumongo 3.0.0

**Comment by evanlucas** [comment]
hm, interesting. I'm not sure how supported Snow Leopard is on node v4+. I know node core's CI does not test it anymore. Have you tried using node v0.10?

**Comment by ddzieduch** [comment]
I had previously installed 0.10.21 version and the same problem has occured.
I thought that an update to the latest node.js version will solve the problem.

**Comment by JoeDoyle23** [comment]
Is this still happening when you run the latest version of this workshopper and a current version of Node?

**Comment by ddzieduch** [comment]
Still not working. Same error message.

OS X 10.6.8
node 4.4.7
learnyoumongo 3.2.0

**Comment by JoeDoyle23** [comment]
Hmm, there's nothing specific about this workshopper that would cause the blinking. Do you see it with other workshoppers as well such as `learnyounode`?

**Comment by ddzieduch** [comment]
Only in this one.

**Comment by JoeDoyle23** [comment]
Ok. I'll try to update this one to use the newer workshopper-adventure modules which might resolve the issue. I'll drop a note where when it's ready to test.
