### ISSUE TITLE
Update lesson fails, even with correct solution

### ISSUE THREAD

**Issue by icodejs** [evanlucas/learnyoumongo#31]
Hey,

While working on the update lesson, I wasn't able to get my code to pass, so I tried your solution and still had no luck.

I not sure if it has something to do with the versions of Node or Mongodb.

Let me know if this is enough information:

Mongodb version v3.2.1
Node v4.2.3

My solution: https://github.com/icodejs/nodeschool/blob/master/learnyoumongo/06-UPDATE/solution.js
Your solution: https://github.com/evanlucas/learnyoumongo/blob/master/exercises/update/solution/solution.js

Thanks!

**Comment by Bubbit** [comment]
I have the same problem:

Mongodb v2.1.7
Node v5.1.0

**Comment by ThomastheBicyclist** [comment]
I have the same problem. I resorted to using the "correct solution" but it didn't pass.

Mongodb v2.6.11
Node v4.1.1

Error message:

```/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/exercises/find/exercise.js:37
  db.collection('parrots').remove({}, function(err) {
    ^

TypeError: Cannot read property 'collection' of undefined
    at Exercise.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/exercises/find/exercise.js:37:5)
    at next (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper-exercise/exercise.js:260:17)
    at Exercise.end (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper-exercise/exercise.js:266:5)
    at Workshopper.end (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper/workshopper.js:191:12)
    at Workshopper.done (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper/workshopper.js:323:19)
    at Exercise.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper-exercise/exercise.js:149:14)
    at /home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper-exercise/exercise.js:136:16
    at Exercise.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/learnyoumongo/node_modules/workshopper-exercise/filecheck.js:10:14)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by kazzacarrot** [comment]
My solution didn't  pass the tests. I saw these comments and doubted the test. So, I pimped out my solution to log tinas record before and after I updated it. I saw her age change from 30 to 40 and when I ran verify, it worked!
I thought I would share my working solution.

```
var mongo = require('mongodb').MongoClient
var url = "mongodb://localhost:27017/" + process.argv[2];
mongo.connect(url, function(err, db) {
    if (err) throw err;
    docs =  db.collection('users')
    tina = {
          username: "tinatime"
        }
    docs.find(tina).toArray(function(err, data) {
            if (err) throw err;
            console.log(data);
            docs.update(tina, { $set: {age: 40 }}, function(err
                    if (err) throw err;
                    docs.find(tina).toArray( function(err, data) {
                            if (err) throw err;
                            db.close()
                            console.log(data);
                        })
                })
    })
})
```

**Comment by midnitedev101** [comment]
Doing the problem on cloud9 server. The solution for UPDATE which is to change the age of 'tinatime' to 40 is not working for me either. Here's my solution which seems to be correct but doesnt work:

`var mongo = require('mongodb').MongoClient;
var url = 'mongodb://localhost:27017/learnyoumongo';

mongo.connect(url, function(err, process.argv[2]) {
        var user = db.collection('users');

        if (err) throw err;

        user.update({
                username: 'tinatime'
        }, {
                $set: {
                        age: 40
                }
        }, function(err, data) {
                if(err) throw err;
                console.log(data);
        });

        db.close();
})`

Still getting this error: 'Document has incorrect age property.Expected: 40 Actual: 30'
