### ISSUE TITLE
Can't get past the first hurdle

### ISSUE THREAD

**Issue by JohnnyBizzel** [evanlucas/learnyoumongo#49]
bizzel:~/workspace $ learnyoumongo verify solution.js
Failed to load c++ bson extension, using pure JS version
/home/ubuntu/workspace/solution.js:28
mongo.connect(url, function(err, db) {
     ^

TypeError: Cannot read property 'connect' of undefined
    at Object.<anonymous> (/home/ubuntu/workspace/solution.js:28:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by cylim** [comment]
@JohnnyBizzel Hi, have you solved the issues?
This link might be useful for you: http://stackoverflow.com/a/24087898

**Comment by evanlucas** [comment]
@JohnnyBizzel can you please paste the contents of solution.js? Thanks!
