### ISSUE TITLE
ReferenceError: done is not defined

### ISSUE THREAD

**Issue by devNoiseConsulting** [evanlucas/learnyoumongo#55]
I'm trying to do the remove exercise on Cloud 9 for freeCodeCamp. For some reason the "done" function is not defined. Any idea what nam module did't get installed?

Versions:
Ubuntu 14.04.5 LTS
Node.js v4.7.3
NPM 2.15.11

```
learnyoumongo verify program07.js 
/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/learnyoumongo/node_modules/mongodb/lib/mongo_client.js:336
          throw err
          ^

ReferenceError: done is not defined
    at /home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/learnyoumongo/exercises/remove/exercise.js:21:21
    at connectCallback (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/learnyoumongo/node_modules/mongodb/lib/mongo_client.js:426:5)
    at /home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/learnyoumongo/node_modules/mongodb/lib/mongo_client.js:333:11
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

**Comment by cyberwichi** [comment]
i have the same problem, any idea?

**Comment by devNoiseConsulting** [comment]
Sorry at this point I don't remember what I did to get past this.
